### ISSUE TITLE
It's possible pass slides with drag n' drop?

### ISSUE THREAD

**Issue by TrejoCode** [dynamicweb/swiffy-slider#3]
Hello, I love the project, but I got a question, it's possible to slide with drag'n drop instead arrows buttons?

In the examples I couldn't find the drag and drop behavior.

**Comment by nicped** [comment]
Hi Sergio

Thank you!

In the current release it is not possible. But I actually have a running example locally on implementing mouse drag.

But I am not sure I want to release it as part of the official package - I do not think that ordinary website users finds it natural to navigate carousels using mouse dragging. I acknowledge that as frontend developers we are fascinated by that particular feature because we understand the implications of implementing it.

Dragging also has a built in UX issue - that when sliding interactive content, i.e. content with clickable buttons and links, things gets confusing because mouse down on that button can mean 2 different things - clicking to activate the button action or to start dragging.  Of course that is not an issue for an image slider.

So - I can release the dragging code I have now as an example so you can easily implement it - looks like this on a hacky animated gif:
![SwiffyDrag](https://user-images.githubusercontent.com/3715307/144117190-8eaf553e-9e90-4961-a274-a2f238c3b5c2.gif)
.

Let me know your input.

**Comment by nicped** [comment]
I have released 1.2.0 that now includes an extension javascript that makes it possible to use dragging.

The configuration has been update to support that.

See an example here: 
[Configuration with mouse drag](https://swiffyslider.com/configuration/?slider-nav-mousedrag=slider-nav-mousedrag&preview-style=preview-images)
