### ISSUE TITLE
Script skips images

### ISSUE THREAD

**Issue by GuyVervilleSpiria** [dynamicweb/swiffy-slider#36]
**Describe the bug**
On a 5 image-slider, the script skips 2 and 4. You can see that the button list below is visited only on 1, 3 and 5. Why?

![CleanShot 2022-04-21 at 08 15 11](https://user-images.githubusercontent.com/69694028/164456720-cbf74aad-b5e5-458e-af8c-e56152ea7717.gif)

The code is as follows:

`<div id="employees" class="swiffy-slider slider-nav-outside slider-nav-visible slider-nav-nodelay slider-nav-autoplay slider-nav-autopause slider-item-show1 slider-indicators-outside slider-nav-animation slider-nav-animation-fadein slider-nav-animation-slow slider-item-last-visible" data-slider-nav-autoplay-interval="5000">
      <ul class="slider-container">
        <li class="employee">
          <img src="https://info.spiria.com/hubfs/Erika.png" alt="Erika">
          <div>
            <div id="hs_cos_wrapper_module_165049619677012_" class="hs_cos_wrapper hs_cos_wrapper_widget hs_cos_wrapper_type_inline_text" style="" data-hs-cos-general-type="widget" data-hs-cos-type="inline_text" data-hs-cos-field="employee_title"></div><br>Erika
          </div>
        </li>
        [...]
      </ul>
      <button type="button" class="slider-nav"></button>
      <button type="button" class="slider-nav slider-nav-next"></button>
      <div class="slider-indicators">
        <button class=""></button>
        <button></button>
        <button class=""></button>
        <button></button>
        <button class="active"></button>
      </div>
    </div>
`

The script is fired this way:

`
window.addEventListener('load', () => {
	swiffyslider.initSlider(document.getElementById('employees'));
});
`

**Comment by pneumotube** [comment]
Hi, thanks for a great slider!

It seems I managed to run into this too (Chrome 102):

https://user-images.githubusercontent.com/4160539/171045653-e411aa46-b5aa-41b4-8c63-062b689cfbed.mp4

[Configurator settings](https://swiffyslider.com/configuration/?slider-nav-style=slider-nav-chevron&slider-nav-dark=slider-nav-dark&slider-nav-arrows=slider-nav-outside&slider-nav-visible=slider-nav-visible&slider-indicators-style=slider-indicators-round&slider-indicators-dark=slider-indicators-dark&slider-indicators-outside=slider-indicators-outside&slider-nav-mousedrag=slider-nav-mousedrag&preview-style=preview-images). I reproduce this issue with this settings on Chrome Canary too.

**Comment by nicped** [comment]
Hi - thanks for trying it out!

I think this problem is 2 things - double loading and initialization of the slider (which happened on the configuration page) and a problem with dragging also reacting when using arrows. Never tested that since I thought you would not combine those.

Made an update of the configuration page that I believe fixes this issue.
https://github.com/dynamicweb/swiffy-slider/commit/c2753596f5b7a293b182719ef369bf706050499e

Will also note that I do not see the dragging feature as a feature that should be used. It is really odd to have mouse dragging on these things (seen from a UX perspective)....

Thanks for giving it a spin and testing things out.

**Comment by pneumotube** [comment]
Okay, noted, thanks. I personally like to drag slider items, it seems to be a more natural movement for me (on the desktop of course). Easier than aiming at arrows :)
