### ISSUE TITLE
Navigation is visible on touch device (phone)

### ISSUE THREAD

**Issue by pneumotube** [dynamicweb/swiffy-slider#41]
When "slider-nav-visible" option is set and "slider-nav-touch" is **not** set, navigation arrows are still visible for me on my phone. They shouldn't be, right?

Android 11, FF, Chrome.

![изображение](https://user-images.githubusercontent.com/4160539/171060465-eff5acfd-40ca-47d6-9485-92485cdc8ce8.png)

**Comment by nicped** [comment]
This is by design - maybe a poor one...

`slider-nav-visible` makes the nav arrows always visible.  `slider-nav-touch` only on mobile.

You can easily add an additional class that will only show the arrows on desktop - i.e. `slider-nav-desktop` by adding this to your code:

@media (hover: hover) {
    .swiffy-slider.slider-nav-desktop .slider-nav {
        visibility: visible;
    }
}
