### ISSUE TITLE
Question about "beforeSlide" event

### ISSUE THREAD

**Issue by digitaldonkey** [dynamicweb/swiffy-slider#44]
Hello,
Is there any way to hook in before slide changes, like a beforeSlide() event. Checked the readme. Did I miss something?

I'm looking for a way to stop a video playing before it plays on somewhere in Background.

**Comment by nicped** [comment]
This is a little tricky since there is no JS starting the scroll - except when clicking the navigation arrows.

There are several options though.

- Since the sliding is a scrollable div, you can listen to the scroll event to ensure you capture all kinds of sliding - clicking the nav arrows, using touch or any of the other supported devices. Then on the slider instance add the `.slider-nav-animation` class to enable that `.slide-visible` will be set on each slide. In you scroll listener, find all videos that does not have `.slide-visible` and stop them
- You can also use an intersection observer on all `.slide-visible` with a video element and when the are no longer intersecting, stop the video.
- Use the `onSlideEnd` event to locate all videos, stop them, and then start the one that is visible.

Hope this can be use!

**Comment by nicped** [comment]
I have looked further into this. I belive you should use an intersection observer to pause all videos out of sight. For the slider or the entire page: 
https://codepen.io/rpsthecoder/pen/ZZLyaG
