### ISSUE TITLE
Infinity scroll 

### ISSUE THREAD

**Issue by Ramil001** [dynamicweb/swiffy-slider#74]
Hello, how i can make infinity scroll slides, i don't find this parameter in docs

**Comment by nicped** [comment]
It is not build in since it requires dom manipulation after load which I am not fan of - so to keep things fast and simple, it is not native.

But it is easy to make though - there is an example of it in the examples section:
[https://swiffyslider.com/examples/#infinite](https://swiffyslider.com/examples/#infinite)

**Comment by Ramil001** [comment]
Thank you
